services:
  # Web Service
  - type: web
    name: r00tglyph
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: r00tglyph-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production

databases:
  # PostgreSQL Database
  - name: r00tglyph-db
    plan: free
    databaseName: r00tglyph
    user: r00tglyph
